version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-tracing-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1s218f8e49vp"
s3_prefix = "aws-tracing-demo"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
